broker:
  # broker gateway host
  host: localhost
  # broker gateway port
  port: 11200
  # unique broker client name
  name: 'bukkit-%unique_id%'
  # default client tags
  tags: ['bukkit', 'server']
  # custom metadata
  metadata:
    #key1: 'value1'
    #key2: 'value2'

server:
  # block remote calls from the main server thread
  thread-check: true
  # optional public game server address
  #host: localhost
  #port: 25565

observability:
  prometheus:
    enabled: false
    host: 0.0.0.0
    port: 9464
