broker:
  # broker gateway host
  host: localhost
  # broker gateway port
  port: 11200
  # unique broker client name
  name: 'velocity-%unique_id%'
  # default client tags
  tags: ['velocity', 'proxy']
  # custom metadata
  metadata:
    #key1: 'value1'
    #key2: 'value2'

player:
  # kick all players when the broker connection closes
  kick-on-close: false

server:
  # sync backend servers to the proxy
  sync-enable: false

observability:
  prometheus:
    enabled: false
    host: 0.0.0.0
    port: 9464
